name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake
        uses: DenverCoder1/github-readme-streak-stats@main

      - run: echo "Snake placeholder workflow works"
